/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.example.TheGioiSua_2024.util;

/**
 *
 * @author Hieu
 */
public class SendMail {

    String token = null;

    public SendMail(String token) {
        this.token = token;
    }

    public String subject = "Xác minh tài khoản của bạn";
    String verificationUrl = "http://localhost:3000/login/" + this.token;
    public String message = "<!DOCTYPE html>\n"
            + "<html lang=\"en\">\n"
            + "<head>\n"
            + "\n"
            + "    <!-- Google Font css -->\n"
            + "    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com/\">\n"
            + "    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Public+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap\">\n"
            + "    <link href=\"https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;400;600;700;800;900&display=swap\" rel=\"stylesheet\">\n"
            + "\n"
            + "    <style type=\"text/css\">\n"
            + "        body {\n"
            + "            text-align: center;\n"
            + "            margin: 0 auto;\n"
            + "            width: 650px;\n"
            + "            font-family: 'Public Sans', sans-serif;\n"
            + "            background-color: #e2e2e2;\n"
            + "            display: block;\n"
            + "        }\n"
            + "\n"
            + "        .mb-3 {\n"
            + "            margin-bottom: 30px;\n"
            + "        }\n"
            + "\n"
            + "        ul {\n"
            + "            margin: 0;\n"
            + "            padding: 0;\n"
            + "        }\n"
            + "\n"
            + "        li {\n"
            + "            display: inline-block;\n"
            + "            text-decoration: unset;\n"
            + "        }\n"
            + "\n"
            + "        a {\n"
            + "            text-decoration: none;\n"
            + "        }\n"
            + "\n"
            + "        h5 {\n"
            + "            margin: 10px;\n"
            + "            color: #777;\n"
            + "        }\n"
            + "\n"
            + "        .text-center {\n"
            + "            text-align: center;\n"
            + "        }\n"
            + "\n"
            + "        .header-menu ul li+li {\n"
            + "            margin-left: 20px;\n"
            + "        }\n"
            + "\n"
            + "        .header-menu ul li a {\n"
            + "            font-size: 14px;\n"
            + "            color: #252525;\n"
            + "            font-weight: 500;\n"
            + "        }\n"
            + "\n"
            + "        .password-button {\n"
            + "            background-color: #0DA487;\n"
            + "            border: none;\n"
            + "            color: #fff;\n"
            + "            padding: 14px 26px;\n"
            + "            font-size: 18px;\n"
            + "            border-radius: 6px;\n"
            + "            font-weight: 700;\n"
            + "            font-family: 'Nunito Sans', sans-serif;\n"
            + "        }\n"
            + "\n"
            + "        .footer-table {\n"
            + "            position: relative;\n"
            + "        }\n"
            + "\n"
            + "        .footer-table::before {\n"
            + "            position: absolute;\n"
            + "            content: \"\";\n"
            + "            background-image: url(images/footer-left.svg);\n"
            + "            background-position: top right;\n"
            + "            top: 0;\n"
            + "            left: -71%;\n"
            + "            width: 100%;\n"
            + "            height: 100%;\n"
            + "            background-repeat: no-repeat;\n"
            + "            z-index: -1;\n"
            + "            background-size: contain;\n"
            + "            opacity: 0.3;\n"
            + "        }\n"
            + "\n"
            + "        .footer-table::after {\n"
            + "            position: absolute;\n"
            + "            content: \"\";\n"
            + "            background-image: url(images/footer-right.svg);\n"
            + "            background-position: top right;\n"
            + "            top: 0;\n"
            + "            right: 0;\n"
            + "            width: 100%;\n"
            + "            height: 100%;\n"
            + "            background-repeat: no-repeat;\n"
            + "            z-index: -1;\n"
            + "            background-size: contain;\n"
            + "            opacity: 0.3;\n"
            + "        }\n"
            + "\n"
            + "        .theme-color {\n"
            + "            color: #0DA487;\n"
            + "        }\n"
            + "    </style>\n"
            + "</head>\n"
            + "\n"
            + "<body style=\"margin: 20px auto;\">\n"
            + "    <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"background-color: white; width: 100%; box-shadow: 0px 0px 14px -4px rgba(0, 0, 0, 0.27);\">\n"
            + "        <tbody>\n"
            + "            <tr>\n"
            + "                <td>\n"
            + "                    <table class=\"content-table\" style=\"margin-bottom: -6px;\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
            + "                        <thead>\n"
            + "                            <tr>\n"
            + "                                <td>\n"
            + "                                    <img src=\"https://i.ibb.co/6ZR8nsm/welcome-poster.jpg\" alt=\"Welcome Poster\" style=\"display: block; margin: 0 auto;\">\n"
            + "                                </td>\n"
            + "                            </tr>\n"
            + "                        </thead>\n"
            + "                    </table>\n"
            + "\n"
            + "                    <table class=\"content-table\" style=\"margin-top: 40px;\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
            + "                        <thead>\n"
            + "                            <tr style=\"display: block;\">\n"
            + "                                <td style=\"display: block;\">\n"
            + "                                    <h3 style=\"font-weight: 700; font-size: 20px; margin: 0; text-transform: uppercase;text-align: center;\">Xin chào bạn và Chào mừng đến với SuaFpoly!</h3>\n"
            + "                                </td>\n"
            + "\n"
            + "                                <td>\n"
            + "                                    <p style=\"font-size: 14px; font-weight: 600; width: 82%; margin: 8px auto 0; line-height: 1.5; color: #939393; font-family: 'Nunito Sans', sans-serif;\">\n"
            + "                                        Chúng tôi hy vọng sản phẩm của chúng tôi sẽ dẫn bạn, như nhiều người trước bạn, đến một nơi mà ý tưởng của bạn có thể nảy sinh và phát triển. Trước khi bắt đầu, chúng tôi cần bạn xác minh email của mình.\n"
            + "                                    </p>\n"
            + "                                </td>\n"
            + "                            </tr>\n"
            + "                        </thead>\n"
            + "                    </table>\n"
            + "\n"
            + "                    <table class=\"button-table\" style=\"margin: 34px 0;\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
            + "                        <thead>\n"
            + "                            <tr style=\"display: block;\">\n"
            + "                                <td style=\"display: block; text-align: center;\">\n"
            + "                    <a href=\"" + verificationUrl + "\" class=\"password-button\">Xác minh Email</a>\n"
            + "                                </td>\n"
            + "                            </tr>\n"
            + "                        </thead>\n"
            + "                    </table>\n"
            + "\n"
            + "                    <table class=\"content-table\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n"
            + "                        <thead>\n"
            + "                            <tr style=\"display: block;\">\n"
            + "                                <td style=\"display: block;\">\n"
            + "                                    <p style=\"font-size: 14px; font-weight: 600; width: 82%; margin: 0 auto; line-height: 1.5; color: #939393; font-family: 'Nunito Sans', sans-serif;\">\n"
            + "                                        Nếu bạn có bất kỳ câu hỏi nào, vui lòng gửi email cho chúng tôi tại <span class=\"theme-color\">suaFpoly</span> hoặc truy cập vào <span class=\"theme-color\">Câu hỏi thường gặp</span>. Bạn cũng có thể trò chuyện với nhân viên trong giờ làm việc để được hỗ trợ.\n"
            + "                                    </p>\n"
            + "                                </td>\n"
            + "                            </tr>\n"
            + "                        </thead>\n"
            + "                    </table>\n"
            + "                </td>\n"
            + "            </tr>\n"
            + "        </tbody>\n"
            + "    </table>\n"
            + "</body>\n"
            + "</html>\n";
}
